const InitialData = {
  "elements": [
    {
      "type": "rectangle",
      "version": 193,
      "versionNonce": 1814220651,
      "isDeleted": false,
      "id": "oDVXy8D6rom3H1-LLH2-f",
      "fillStyle": "hachure",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "angle": 0,
      "x": 100,
      "y": 100,
      "strokeColor": "#c92a2a",
      "backgroundColor": "transparent",
      "width": 196.07266235351557,
      "height": 220,
      "seed": 1968410350,
      "groupIds": [],
      "updated": 1680114199998
    },
    {
      "id": "e8nqonDvp0fPD_Z3eyN_q",
      "type": "text",
      "x": 120,
      "y": 100,
      "width": 176,
      "height": 50,
      "angle": 0,
      "strokeColor": "#c92a2a",
      "backgroundColor": "transparent",
      "fillStyle": "hachure",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "groupIds": [],
      "roundness": null,
      "seed": 450665561,
      "version": 147,
      "versionNonce": 1300288203,
      "isDeleted": false,
      "boundElements": null,
      "updated": 1680114411867,
      "link": null,
      "locked": false,
      "text": "words have tried \n",
      "fontSize": 20,
      "fontFamily": 1,
      "textAlign": "left",
      "verticalAlign": "top",
      "baseline": 42,
      "containerId": null,
      "originalText": "words have tried \n"
    },
    {
      "id": "NzlwfnRGcNa6RsHfv4tuX",
      "type": "text",
      "x": 120,
      "y": 340,
      "width": 128,
      "height": 25,
      "angle": 0,
      "strokeColor": "#5f3dc4",
      "backgroundColor": "transparent",
      "fillStyle": "hachure",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "groupIds": [],
      "roundness": null,
      "seed": 1383859703,
      "version": 188,
      "versionNonce": 251106635,
      "isDeleted": false,
      "boundElements": null,
      "updated": 1680114420377,
      "link": null,
      "locked": false,
      "text": "words to try",
      "fontSize": 20,
      "fontFamily": 1,
      "textAlign": "left",
      "verticalAlign": "top",
      "baseline": 18,
      "containerId": null,
      "originalText": "words to try"
    },
    {
      "type": "rectangle",
      "version": 203,
      "versionNonce": 1862755909,
      "isDeleted": false,
      "id": "uxzazbdh35wWzEiepKyZ2",
      "fillStyle": "hachure",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "angle": 0,
      "x": 100,
      "y": 340,
      "strokeColor": "#5f3dc4",
      "backgroundColor": "transparent",
      "width": 196.07266235351557,
      "height": 220,
      "seed": 1644560517,
      "groupIds": [],
      "roundness": null,
      "boundElements": null,
      "updated": 1680114199998,
      "link": null,
      "locked": false
    },
    {
      "type": "rectangle",
      "version": 205,
      "versionNonce": 1950141579,
      "isDeleted": false,
      "id": "LNXTCiuW2vUyuX7bvEeJB",
      "fillStyle": "hachure",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "angle": 0,
      "x": 320,
      "y": 100,
      "strokeColor": "#e67700",
      "backgroundColor": "transparent",
      "width": 196.07266235351557,
      "height": 220,
      "seed": 1575302027,
      "groupIds": [],
      "roundness": null,
      "boundElements": null,
      "updated": 1680114199998,
      "link": null,
      "locked": false
    },
    {
      "type": "text",
      "version": 166,
      "versionNonce": 1035787275,
      "isDeleted": false,
      "id": "SYd8xa4ecU7BVHfrpELzE",
      "fillStyle": "hachure",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "angle": 0,
      "x": 320,
      "y": 100,
      "strokeColor": "#e67700",
      "backgroundColor": "transparent",
      "width": 185,
      "height": 50,
      "seed": 1869500875,
      "groupIds": [],
      "roundness": null,
      "boundElements": null,
      "updated": 1680114414481,
      "link": null,
      "locked": false,
      "fontSize": 20,
      "fontFamily": 1,
      "text": "YELLOW LETTERS\nWITH POSITION",
      "baseline": 42,
      "textAlign": "left",
      "verticalAlign": "top",
      "containerId": null,
      "originalText": "YELLOW LETTERS\nWITH POSITION"
    },
    {
      "type": "rectangle",
      "version": 214,
      "versionNonce": 711603941,
      "isDeleted": false,
      "id": "7NMaZDPpLj96uzrhIcJCa",
      "fillStyle": "hachure",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "angle": 0,
      "x": 320,
      "y": 340,
      "strokeColor": "#5c940d",
      "backgroundColor": "transparent",
      "width": 199.99999999999994,
      "height": 220,
      "seed": 554323813,
      "groupIds": [],
      "roundness": null,
      "boundElements": null,
      "updated": 1680114353036,
      "link": null,
      "locked": false
    },
    {
      "type": "text",
      "version": 235,
      "versionNonce": 401247979,
      "isDeleted": false,
      "id": "66W2JQ3iiJ0DXj6O1vf2g",
      "fillStyle": "hachure",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "angle": 0,
      "x": 320,
      "y": 340,
      "strokeColor": "#5c940d",
      "backgroundColor": "transparent",
      "width": 177,
      "height": 50,
      "seed": 1701244293,
      "groupIds": [],
      "roundness": null,
      "boundElements": null,
      "updated": 1680114402785,
      "link": null,
      "locked": false,
      "fontSize": 20,
      "fontFamily": 1,
      "text": "GREEN LETTERS\nWITH POSITION",
      "baseline": 42,
      "textAlign": "left",
      "verticalAlign": "top",
      "containerId": null,
      "originalText": "GREEN LETTERS\nWITH POSITION"
    }
  ],
  "appState": {
    "gridSize": null,
    "viewBackgroundColor": "#edf2ff"
  }
};

export default InitialData;